### PR TITLE
fix: RPOP bug

### PR DESCRIPTION
**Pull request by b41sh**
fix RPOP bug [199](https://github.com/distributedio/titan/issues/199)

### CODE REVIEW

**Comment by arthurkiller** [comment]
hi, have you test with this?

**Comment by arthurkiller** [comment]
in my environment
```
pingcap/pd            latest              1960f60dd4bd        7 weeks ago         81.3MB
pingcap/tikv          latest              7e393dda4bdb        7 weeks ago         373MB

tidb sdk
github.com/pingcap/tidb v1.1.0-beta.0.20191227152506-8f13cf1449bd
```
problem still occour
```
127.0.0.1:7369> del foo
(integer) 1
127.0.0.1:7369> lpush foo 1 2 3
(integer) 3
127.0.0.1:7369> rpop foo
"2"
127.0.0.1:7369> rpop foo
(error) ERR key not found
```

**Comment by b41sh** [comment]
I have tested, My tikv  version is 4622c2e97f6bab01618398bc767569c62279090a.
This version is a little bit old. I'll test it with the latest version

**Comment by arthurkiller** [comment]
> I have tested, My tikv version is 4622c2e97f6bab01618398bc767569c62279090a.
> This version is a little bit old. I'll test it with the latest version

Test has passed

**Pull request merged**
